# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  -
    main: ./cmd/plutos/main.go
    binary: plutos
    goarch:
      - amd64
  -
    main: ./cmd/plutoapi/main.go
    binary: plutoapi
    goarch:
      - amd64
  -
    main: ./cmd/sqldb/main.go
    binary: plutosqldb
    goarch:
      - amd64
  -
    main: ./cmd/plutoclient/main.go
    binary: plutoclient
    goarch:
      - amd64
archive:
  format: zip
  replacements:
    linux: Linux
    amd64: x86_64
    darwin: macOS
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  draft: true
dockers:
  -
    binaries:
    - plutos
    - plutoapi
    - plutosqldb
    - plutoclient
    image_templates:
    - "qiwitech/qdp:{{ .Tag }}"
    - "qiwitech/qdp:latest"
